version: '3.8'

services:
  # Banco de Dados para persistência da Telemetria
  db:
    image: postgres:16-alpine
    container_name: justina_db
    restart: always
    environment:
      POSTGRES_DB: justina_db
      POSTGRES_USER: user_justina
      POSTGRES_PASSWORD: password_justina
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Backend Java (Spring Boot + Clean Arch)
  backend_telemetry:
    build: ./backend_telemetry
    container_name: justina_backend
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/justina_db
      - SPRING_DATASOURCE_USERNAME=user_justina
      - SPRING_DATASOURCE_PASSWORD=password_justina
      - AI_SERVICE_URL=http://ai_service:8000
    networks:
      - justina_network

  # IA Service (Python + FastAPI + PyTorch)
  ai_service:
    build: ./ai_service
    container_name: justina_ai
    restart: on-failure
    ports:
      - "8000:8000"
    volumes:
      - ./ai_service/app:/app
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY} # Pega do seu arquivo .env local
    networks:
      - justina_network

  # Frontend (React ou Streamlit)
  simulator_frontend:
    build: ./simulator_frontend
    container_name: justina_frontend
    restart: on-failure
    ports:
      - "3000:3000" # Se for React
      # - "8501:8501" # Se optar por Streamlit, altere a porta
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - backend_telemetry
    networks:
      - justina_network

networks:
  justina_network:
    driver: bridge

volumes:
  postgres_data: