
spring.application.name=JustinaBackend

# Porta do Java
server.port=8081

# Configuração do Serviço Python (AI Service)
app.ai-service.url=http://localhost:5000

# Configuração básica de banco em memória (H2) para teste rápido
spring.datasource.url=jdbc:h2:mem:justinadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true