# Em produção, o nome e a porta geralmente são definidos pelo servidor
spring.application.name=JustinaBackend-Prod
server.port=8081

# Banco de Dados Real (PostgreSQL)
# Usamos variáveis ${} para não expor senhas no GitHub
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/justina_db}
spring.datasource.username=${DB_USER:user_justina}
spring.datasource.password=${DB_PASSWORD:password_justina}
spring.datasource.driverClassName=org.postgresql.Driver

# Hibernate para Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# URL da IA em Produção (Onde o Python estiver rodando)
app.ai-service.url=${AI_SERVICE_URL}